<a href="https://colab.research.google.com/github/divyansh1195/Kaggle-ML-Exercise-Notebooks/blob/master/Kaggle_Intro_to_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ML Models : 
Decision Tree and Random Forest**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import seaborn as sns

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
#loading the dataset
home_data = pd.read_csv('train.csv')
home_data.columns #gives columns in teh dataset 

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

In [ ]:
y = home_data.SalePrice.values
feature_columns = ['LotArea', 'YearBuilt', '1stFlrSF', '2ndFlrSF', 'FullBath', 'BedroomAbvGr', 'TotRmsAbvGrd']
X = home_data[feature_columns].values
print(X)
print(y)

[[ 8450  2003   856 ...     2     3     8]
 [ 9600  1976  1262 ...     2     3     6]
 [11250  2001   920 ...     2     3     6]
 ...
 [ 9042  1941  1188 ...     2     4     9]
 [ 9717  1950  1078 ...     1     2     5]
 [ 9937  1965  1256 ...     1     3     6]]
[208500 181500 223500 ... 266500 142125 147500]


**DECISION TREE REGRESSOR**

In [ ]:
from sklearn.tree import DecisionTreeRegressor
iowa_model = DecisionTreeRegressor(random_state=0)
iowa_model.fit(X, y)
predictions=iowa_model.predict(X)
np.set_printoptions(precision=2)
print(np.concatenate((predictions.reshape(len(predictions),1), y.reshape(len(y),1)),1))

[[208500. 208500.]
 [181500. 181500.]
 [223500. 223500.]
 ...
 [266500. 266500.]
 [142125. 142125.]
 [147500. 147500.]]


**Model Validation**

Insample Mean Absolute error is wrong!!!

In [ ]:
#Calculate the Mean Absolute Error in  In-Sample Data
from sklearn.metrics import mean_absolute_error
val_mae_insample = mean_absolute_error(y,predictions)
print(val_mae_insample)

62.35433789954339


Since models' practical value come from making predictions on new data, we measure performance on data that wasn't used to build the model. The most straightforward way to do this is to exclude some data from the model-building process, and then use those to test the model's accuracy on data it hasn't seen before. This data is called validation data i.e. splitting the data into training set and test set.

Model validation

In [ ]:
# Import the train_test_split function and uncomment
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=1)
# Specify the model
model_iowa = DecisionTreeRegressor(random_state=1)

# Fit iowa_model with the training data.
model_iowa.fit(X_train, y_train)

# Predict with all X_test observations
y_pred = model_iowa.predict(X_test)

#Inspect your predictions and actual values from the housing data
np.set_printoptions(precision=2)
#print(y_test)
#print(y_pred)

#comapre y_pred and y_test values
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[195000. 231500.]
 [108000. 179500.]
 [130000. 122000.]
 [ 81000.  84500.]
 [177000. 142000.]
 [235128. 325624.]
 [333168. 285000.]
 [144152. 151000.]
 [215000. 195000.]
 [179200. 275000.]
 [182900. 175000.]
 [ 99900.  61000.]
 [192500. 174000.]
 [242000. 385000.]
 [278000. 230000.]
 [100000.  87000.]
 [138500. 125000.]
 [139950.  98600.]
 [194000. 260000.]
 [156000. 143000.]
 [150500. 124000.]
 [325000. 122500.]
 [270000. 236500.]
 [377500. 337500.]
 [134900.  76000.]
 [140000. 187000.]
 [119500. 128000.]
 [192000. 179000.]
 [582933. 485000.]
 [148500. 122500.]
 [140000. 106000.]
 [ 91500. 118000.]
 [112500. 127000.]
 [ 82500.  80000.]
 [123000. 153000.]
 [386250. 360000.]
 [110000. 132000.]
 [ 99900.  85500.]
 [305000. 262280.]
 [ 84000. 112000.]
 [125000. 131000.]
 [134450. 139000.]
 [110000.  87000.]
 [100000. 135000.]
 [168000. 181000.]
 [150900. 163500.]
 [ 88000. 116900.]
 [176485. 159895.]
 [225000. 244600.]
 [235000. 294000.]
 [132000.  97000.]
 [475000. 295000.]
 [110000. 12

In [ ]:
#Calculate the Mean Absolute Error in Data
from sklearn.metrics import mean_absolute_error
val_mae = mean_absolute_error(y_test, y_pred)
print("Validation MAE($): {:,.0f}".format(val_mae))

Validation MAE($): 30,643


**Underfitting and Overfitting**

Overfitting: capturing spurious patterns that won't recur in the future, leading to less accurate predictions 

Underfitting: failing to capture relevant patterns, again leading to less accurate predictions.

We use validation data, which isn't used in model training, to measure a candidate model's accuracy. This lets us try many candidate models and keep the best one.

In [ ]:
def get_mae(max_leaf_nodes, X_train, X_test, y_train, y_test):
    model = DecisionTreeRegressor(max_leaf_nodes=max_leaf_nodes, random_state=0)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    mae = mean_absolute_error(y_test, y_pred)
    return(mae)
candidate_max_leaf_nodes = [5, 25, 50, 100, 250, 500, 750, 1000, 1500]
for max_leaf_nodes in candidate_max_leaf_nodes:
  best_mae = get_mae(max_leaf_nodes,X_train, X_test, y_train, y_test)
  print("Max leaf nodes: %d  \t\t Mean Absolute Error:  %d" %(max_leaf_nodes, best_mae))

Max leaf nodes: 5  		 Mean Absolute Error:  35436
Max leaf nodes: 25  		 Mean Absolute Error:  29324
Max leaf nodes: 50  		 Mean Absolute Error:  28003
Max leaf nodes: 100  		 Mean Absolute Error:  27803
Max leaf nodes: 250  		 Mean Absolute Error:  29711
Max leaf nodes: 500  		 Mean Absolute Error:  30400
Max leaf nodes: 750  		 Mean Absolute Error:  30867
Max leaf nodes: 1000  		 Mean Absolute Error:  30990
Max leaf nodes: 1500  		 Mean Absolute Error:  30966


We know the best tree size. If we are going to deploy this model in practice, we would make it even more accurate by using all of the data and keeping that tree size. That is, we don't need to hold out the validation data now that we've made all our modeling decisions.

In [ ]:
#now fit the model to the X_train and y_train with best tree size
final_model = DecisionTreeRegressor(max_leaf_nodes=100, random_state=0)
final_model.fit(X_train,y_train)
# Predict with all X_test observations
y_pred = final_model.predict(X_test)

#Inspect your predictions and actual values from the housing data
np.set_printoptions(precision=2)
#comapre y_pred and y_test values
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

In [ ]:
#now fit the model to the whole dataset with best tree size
#In theory, this should get much better results than previous 2 as it is trained on whole dataset
model=DecisionTreeRegressor(max_leaf_nodes=100, random_state=0)
model.fit(X,y)
y_prediction=model.predict(X)
np.set_printoptions(precision=2)
print(np.concatenate((y_prediction.reshape(len(y_prediction),1), y.reshape(len(y),1)),1))

[[209133.65 208500.  ]
 [146415.01 181500.  ]
 [209133.65 223500.  ]
 ...
 [238763.64 266500.  ]
 [130629.   142125.  ]
 [146415.01 147500.  ]]


**RANDOM FOREST REGRESSOR**

In [ ]:
# Import the train_test_split function and uncomment
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=1)
# Specify the model
from sklearn.ensemble import RandomForestRegressor
model_rfr = RandomForestRegressor(random_state=1)

# Fit iowa_model with the training data.
model_rfr.fit(X_train, y_train)

# Predict with all X_test observations
y_pred = model_rfr.predict(X_test)

#Inspect your predictions and actual values from the housing data
np.set_printoptions(precision=2)
#print(y_test)
#print(y_pred)

#comapre y_pred and y_test values
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

#calculate mean absolute error
from sklearn.metrics import mean_absolute_error
value_rfr_mae = mean_absolute_error(y_test, y_pred)
print("Validation MAE($): {:,.0f}".format(value_rfr_mae))

[[196941.65 231500.  ]
 [147818.   179500.  ]
 [129379.08 122000.  ]
 [ 85505.    84500.  ]
 [150151.5  142000.  ]
 [273221.2  325624.  ]
 [328546.24 285000.  ]
 [146899.38 151000.  ]
 [216315.05 195000.  ]
 [224342.   275000.  ]
 [172243.55 175000.  ]
 [104164.72  61000.  ]
 [219098.11 174000.  ]
 [251084.44 385000.  ]
 [257950.77 230000.  ]
 [110349.04  87000.  ]
 [112567.5  125000.  ]
 [146058.    98600.  ]
 [193355.54 260000.  ]
 [137974.67 143000.  ]
 [148493.5  124000.  ]
 [186211.93 122500.  ]
 [225478.   236500.  ]
 [323742.76 337500.  ]
 [102934.    76000.  ]
 [167113.   187000.  ]
 [120431.5  128000.  ]
 [194559.58 179000.  ]
 [499317.24 485000.  ]
 [123477.34 122500.  ]
 [139854.28 106000.  ]
 [ 99179.58 118000.  ]
 [121814.   127000.  ]
 [110288.    80000.  ]
 [138323.5  153000.  ]
 [332372.15 360000.  ]
 [111756.25 132000.  ]
 [106987.71  85500.  ]
 [285568.86 262280.  ]
 [113825.5  112000.  ]
 [141027.   131000.  ]
 [129672.75 139000.  ]
 [104018.75  87000.  ]
 [113069.5 

This Random Forest Regressor shows better result on test datasets when compared with Decision Tree Regressor